version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
    reviewers:
      - "seyedeliasfakoorian"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "github actions"
      - "dependencies"
    reviewers:
      - "seyedeliasfakoorian"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    labels:
      - "dependencies"
    reviewers:
      - "seyedeliasfakoorian"
    schedule:
      interval: "daily"