# Specify the package manager for your project
package_manager: "npm"

# Define the strategy for dependency updates
update_strategy:
  default: "reduce"
target_branch: "main"
schedule:
  interval: "daily"

dependencies:
  - type: "dependencies"
  - type: "devDependencies"

pull_requests:
  auto_merge: false
  branch_name: "depfu"
  title: "bump <dependency> from <from_version> to <to_version>"
  labels:
    - "depfu"
  reviewers:
    - "seyedeliasfakoorian"
  post_update_commands:
    - "npm install"