name: "Org2 1"

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Test
      run: npm test
